GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/7907 HTTP/1.1
###
PUT http://localhost:3001/api/persons/8567 HTTP/1.1
content-type: text/html

{
    "name": "x",
    "number": "2313-21389312",
    "id":8567
}

